### ISSUE TITLE
Picture upload

### ISSUE THREAD

**Issue by bbabel** [Espenhh/Slidifier#9]
I want to use Slidefier to local presentations. Everything was going well until I tried to upload a picture: If I choose an image and hit the upload button, Firefox tells me to download io.php file. If I hit open it opens another tab and ask me to do the same in an infinite loop. If I choose download I end up with a io.php file in my download folder.

What's the right way to upload files to my presentation? Or even better, what's the correct way to link files in the uploaded_files folder to slidefier.html.

Thanks

**Comment by holgerl** [comment]
Actually, picture uploading can only work when Slidifier is hosted online. That means that it will never work when you do local presentations. For that you have to use slidifier.com online. But, if you have an url to the image then you can use the "enter picture url" button to insert it.

If you have the url to the image in the uploaded_files folder, then you can enter something like this in the slides to show the image:

```
<img src="http://slidifier.com/uploaded_files/yourpicturenamehere.jpg"/>
```

**Comment by bbabel** [comment]
Ok, I get it now. So this is actually not an issue, but just the way it works. Thanks for clarifying that.
